'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.34014
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FileDeploymentTool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property FileEncrypterAndDecrypter() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FileEncrypterAndDecrypter", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Byte[] のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property FileHacker() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FileHacker", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  &lt;Questions&gt;
        '''	&lt;Question&gt;
        '''		&lt;Text&gt;readの過去形は？&lt;/Text&gt;
        '''		&lt;Tip&gt;全て小文字で答えなさい&lt;/Tip&gt;
        '''		&lt;Answer&gt;read&lt;/Answer&gt;
        '''	&lt;/Question&gt;
        '''	&lt;Question&gt;
        '''		&lt;Text&gt;林檎　これどう読む？&lt;/Text&gt;
        '''		&lt;Tip&gt;ひらがなで答えなさい&lt;/Tip&gt;
        '''		&lt;Answer&gt;りんご&lt;/Answer&gt;
        '''	&lt;/Question&gt;
        '''	&lt;Question&gt;
        '''		&lt;Text&gt;「魚」へんに「弱」い。//なんて読む？&lt;/Text&gt;
        '''		&lt;Tip&gt;ひらがなで答えなさい&lt;/Tip&gt;
        '''		&lt;Answer&gt;いわし&lt;/Answer&gt;
        '''	&lt;/Question&gt;
        '''	&lt;Question&gt;
        '''		&lt;Text&gt;Japanはどこ？//こそあど言葉で答えなさい&lt;/Text&gt;
        '''		&lt;Tip&gt;ひらがなで答えなさい&lt;/Tip&gt;
        '''		&lt;Answer&gt;ここ&lt;/Answer&gt;
        '''	&lt;/Question&gt;
        '''	&lt;Question&gt;
        '''		&lt;Text&gt;韓国は栃木県からして八方位からどこ？&lt;/Text&gt;
        '''		&lt;Tip&gt;漢字で答えなさい&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property VerifyQuestions() As String
            Get
                Return ResourceManager.GetString("VerifyQuestions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Fuck
        '''fuck
        '''madness
        '''Madness
        '''protect
        '''frOm
        '''trust
        '''trUst
        '''saFe
        '''GaMe
        '''Triangle
        '''Chip
        '''Dale
        '''Cheat
        '''cheaT
        '''taehc
        '''Servant
        '''Queen
        '''Android
        '''Andrpid
        '''android
        '''andrpid
        '''servant
        '''quEEn
        '''Encyclopedia
        '''Uncyclopedia
        '''Encyclpoedia
        '''Uncyclpoedia
        '''Wikipedia
        '''Wikileaks
        '''Phone
        '''Tablet
        '''FileHacker
        '''Windows
        '''Desktop
        '''Brioche
        '''Visual
        '''Studio
        '''File
        '''Hacker
        '''Lie
        '''lie
        '''license
        '''operating
        '''run
        '''do
        '''fplder
        '''folder に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property VerifyStrings() As String
            Get
                Return ResourceManager.GetString("VerifyStrings", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
